/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author Norangel Marin
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        tituloPrincipal = new javax.swing.JLabel();
        btnStartSimulation = new javax.swing.JButton();
        btnStopSimulation = new javax.swing.JButton();
        panelColasBugatti = new javax.swing.JPanel();
        tituloColasBugatti = new javax.swing.JLabel();
        textCalidadBajaBugatti = new javax.swing.JTextField();
        textCalidadMediaBugatti = new javax.swing.JTextField();
        textCalidadAltaBugatti = new javax.swing.JTextField();
        alta = new javax.swing.JLabel();
        baja = new javax.swing.JLabel();
        media = new javax.swing.JLabel();
        panelCarrera = new javax.swing.JPanel();
        titulo40 = new javax.swing.JLabel();
        titulo41 = new javax.swing.JLabel();
        textDaysRemainingBu8 = new javax.swing.JTextField();
        textDaysRemainingBu9 = new javax.swing.JTextField();
        panelColasLamborguini = new javax.swing.JPanel();
        titulo6 = new javax.swing.JLabel();
        textDaysRemainingBu5 = new javax.swing.JTextField();
        textDaysRemainingBu6 = new javax.swing.JTextField();
        textDaysRemainingBu7 = new javax.swing.JTextField();
        titulo35 = new javax.swing.JLabel();
        titulo36 = new javax.swing.JLabel();
        titulo37 = new javax.swing.JLabel();
        panelIA = new javax.swing.JPanel();
        titulo62 = new javax.swing.JLabel();
        textDaysRemainingBu1 = new javax.swing.JTextField();
        titulo63 = new javax.swing.JLabel();
        panelMarcadorGanadores = new javax.swing.JPanel();
        titulo61 = new javax.swing.JLabel();
        titulo30 = new javax.swing.JLabel();
        titulo31 = new javax.swing.JLabel();
        textEEarningsBu = new javax.swing.JTextField();
        textECostBu = new javax.swing.JTextField();
        titulo64 = new javax.swing.JLabel();
        panelTiempo = new javax.swing.JPanel();
        titulo60 = new javax.swing.JLabel();
        textDaysRemainingBu = new javax.swing.JTextField();
        titulo59 = new javax.swing.JLabel();
        buttonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        PanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        PanelPrincipal.setForeground(new java.awt.Color(255, 255, 204));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        tituloPrincipal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        tituloPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        tituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPrincipal.setText("Simulación de Carreras");
        PanelPrincipal.add(tituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 740, 40));

        btnStartSimulation.setBackground(new java.awt.Color(0, 0, 0));
        btnStartSimulation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStartSimulation.setForeground(new java.awt.Color(255, 255, 255));
        btnStartSimulation.setText("Iniciar Simulación");
        btnStartSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartSimulationActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnStartSimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 340, 30));

        btnStopSimulation.setBackground(new java.awt.Color(0, 0, 0));
        btnStopSimulation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStopSimulation.setForeground(new java.awt.Color(255, 255, 255));
        btnStopSimulation.setText("Terminar Simulación");
        btnStopSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopSimulationActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnStopSimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 340, 30));

        panelColasBugatti.setBackground(new java.awt.Color(255, 102, 102));
        panelColasBugatti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasBugatti.setForeground(new java.awt.Color(0, 0, 0));
        panelColasBugatti.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloColasBugatti.setBackground(new java.awt.Color(0, 0, 0));
        tituloColasBugatti.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        tituloColasBugatti.setForeground(new java.awt.Color(0, 0, 0));
        tituloColasBugatti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloColasBugatti.setText("Colas de Calidad Bugatti");
        panelColasBugatti.add(tituloColasBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 310, 20));

        textCalidadBajaBugatti.setEditable(false);
        textCalidadBajaBugatti.setBackground(new java.awt.Color(255, 255, 255));
        textCalidadBajaBugatti.setForeground(new java.awt.Color(0, 0, 0));
        textCalidadBajaBugatti.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCalidadBajaBugatti.setToolTipText("");
        textCalidadBajaBugatti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasBugatti.add(textCalidadBajaBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 310));

        textCalidadMediaBugatti.setEditable(false);
        textCalidadMediaBugatti.setBackground(new java.awt.Color(255, 255, 255));
        textCalidadMediaBugatti.setForeground(new java.awt.Color(0, 0, 0));
        textCalidadMediaBugatti.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCalidadMediaBugatti.setToolTipText("");
        textCalidadMediaBugatti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasBugatti.add(textCalidadMediaBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, 310));

        textCalidadAltaBugatti.setEditable(false);
        textCalidadAltaBugatti.setBackground(new java.awt.Color(255, 255, 255));
        textCalidadAltaBugatti.setForeground(new java.awt.Color(0, 0, 0));
        textCalidadAltaBugatti.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCalidadAltaBugatti.setToolTipText("");
        textCalidadAltaBugatti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasBugatti.add(textCalidadAltaBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 90, 310));

        alta.setBackground(new java.awt.Color(0, 0, 0));
        alta.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        alta.setForeground(new java.awt.Color(0, 0, 0));
        alta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alta.setText("Alta");
        panelColasBugatti.add(alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 90, -1));

        baja.setBackground(new java.awt.Color(0, 0, 0));
        baja.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        baja.setForeground(new java.awt.Color(0, 0, 0));
        baja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baja.setText("Baja");
        panelColasBugatti.add(baja, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 90, -1));

        media.setBackground(new java.awt.Color(0, 0, 0));
        media.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        media.setForeground(new java.awt.Color(0, 0, 0));
        media.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        media.setText("Media");
        panelColasBugatti.add(media, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 90, -1));

        PanelPrincipal.add(panelColasBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 310, 390));

        panelCarrera.setBackground(new java.awt.Color(255, 102, 102));
        panelCarrera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCarrera.setForeground(new java.awt.Color(0, 0, 0));
        panelCarrera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo40.setBackground(new java.awt.Color(0, 0, 0));
        titulo40.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo40.setForeground(new java.awt.Color(0, 0, 0));
        titulo40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo40.setText("(Vehiculos en la IA)");
        panelCarrera.add(titulo40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 20));

        titulo41.setBackground(new java.awt.Color(0, 0, 0));
        titulo41.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo41.setForeground(new java.awt.Color(0, 0, 0));
        titulo41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo41.setText("Carrera");
        panelCarrera.add(titulo41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 20));

        textDaysRemainingBu8.setEditable(false);
        textDaysRemainingBu8.setBackground(new java.awt.Color(255, 255, 255));
        textDaysRemainingBu8.setForeground(new java.awt.Color(0, 0, 0));
        textDaysRemainingBu8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textDaysRemainingBu8.setToolTipText("");
        textDaysRemainingBu8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCarrera.add(textDaysRemainingBu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, 50));

        textDaysRemainingBu9.setEditable(false);
        textDaysRemainingBu9.setBackground(new java.awt.Color(255, 255, 255));
        textDaysRemainingBu9.setForeground(new java.awt.Color(0, 0, 0));
        textDaysRemainingBu9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textDaysRemainingBu9.setToolTipText("");
        textDaysRemainingBu9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCarrera.add(textDaysRemainingBu9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 50));

        PanelPrincipal.add(panelCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 300, 140));

        panelColasLamborguini.setBackground(new java.awt.Color(255, 102, 102));
        panelColasLamborguini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasLamborguini.setForeground(new java.awt.Color(0, 0, 0));
        panelColasLamborguini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo6.setBackground(new java.awt.Color(0, 0, 0));
        titulo6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo6.setForeground(new java.awt.Color(0, 0, 0));
        titulo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo6.setText("Colas de Calidad Lamborguini");
        panelColasLamborguini.add(titulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 310, 20));

        textDaysRemainingBu5.setEditable(false);
        textDaysRemainingBu5.setBackground(new java.awt.Color(255, 255, 255));
        textDaysRemainingBu5.setForeground(new java.awt.Color(0, 0, 0));
        textDaysRemainingBu5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textDaysRemainingBu5.setToolTipText("");
        textDaysRemainingBu5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textDaysRemainingBu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDaysRemainingBu5ActionPerformed(evt);
            }
        });
        panelColasLamborguini.add(textDaysRemainingBu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 310));

        textDaysRemainingBu6.setEditable(false);
        textDaysRemainingBu6.setBackground(new java.awt.Color(255, 255, 255));
        textDaysRemainingBu6.setForeground(new java.awt.Color(0, 0, 0));
        textDaysRemainingBu6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textDaysRemainingBu6.setToolTipText("");
        textDaysRemainingBu6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasLamborguini.add(textDaysRemainingBu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 90, 310));

        textDaysRemainingBu7.setEditable(false);
        textDaysRemainingBu7.setBackground(new java.awt.Color(255, 255, 255));
        textDaysRemainingBu7.setForeground(new java.awt.Color(0, 0, 0));
        textDaysRemainingBu7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textDaysRemainingBu7.setToolTipText("");
        textDaysRemainingBu7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasLamborguini.add(textDaysRemainingBu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, 310));

        titulo35.setBackground(new java.awt.Color(0, 0, 0));
        titulo35.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        titulo35.setForeground(new java.awt.Color(0, 0, 0));
        titulo35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo35.setText("Media");
        panelColasLamborguini.add(titulo35, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 90, -1));

        titulo36.setBackground(new java.awt.Color(0, 0, 0));
        titulo36.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        titulo36.setForeground(new java.awt.Color(0, 0, 0));
        titulo36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo36.setText("Baja");
        panelColasLamborguini.add(titulo36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 90, -1));

        titulo37.setBackground(new java.awt.Color(0, 0, 0));
        titulo37.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        titulo37.setForeground(new java.awt.Color(0, 0, 0));
        titulo37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo37.setText("Alta");
        panelColasLamborguini.add(titulo37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 90, -1));

        PanelPrincipal.add(panelColasLamborguini, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 310, 390));

        panelIA.setBackground(new java.awt.Color(255, 102, 102));
        panelIA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelIA.setForeground(new java.awt.Color(0, 0, 0));
        panelIA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo62.setBackground(new java.awt.Color(0, 0, 0));
        titulo62.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo62.setForeground(new java.awt.Color(0, 0, 0));
        titulo62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo62.setText("IA");
        panelIA.add(titulo62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 20));

        textDaysRemainingBu1.setEditable(false);
        textDaysRemainingBu1.setBackground(new java.awt.Color(255, 255, 255));
        textDaysRemainingBu1.setForeground(new java.awt.Color(0, 0, 0));
        textDaysRemainingBu1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textDaysRemainingBu1.setToolTipText("");
        textDaysRemainingBu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelIA.add(textDaysRemainingBu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, 30));

        titulo63.setBackground(new java.awt.Color(0, 0, 0));
        titulo63.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo63.setForeground(new java.awt.Color(0, 0, 0));
        titulo63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo63.setText("Gestion de Trabajo");
        panelIA.add(titulo63, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 260, 20));

        PanelPrincipal.add(panelIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 300, 90));

        panelMarcadorGanadores.setBackground(new java.awt.Color(255, 102, 102));
        panelMarcadorGanadores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMarcadorGanadores.setForeground(new java.awt.Color(0, 0, 0));
        panelMarcadorGanadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo61.setBackground(new java.awt.Color(0, 0, 0));
        titulo61.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo61.setForeground(new java.awt.Color(0, 0, 0));
        titulo61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo61.setText("(Conteo de carreras ganadas)");
        panelMarcadorGanadores.add(titulo61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 20));

        titulo30.setBackground(new java.awt.Color(0, 0, 0));
        titulo30.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        titulo30.setForeground(new java.awt.Color(0, 0, 0));
        titulo30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo30.setText("Lamborguini");
        panelMarcadorGanadores.add(titulo30, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 110, -1));

        titulo31.setBackground(new java.awt.Color(0, 0, 0));
        titulo31.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        titulo31.setForeground(new java.awt.Color(0, 0, 0));
        titulo31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo31.setText("Bugatti");
        panelMarcadorGanadores.add(titulo31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, -1));

        textEEarningsBu.setEditable(false);
        textEEarningsBu.setBackground(new java.awt.Color(255, 255, 255));
        textEEarningsBu.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        textEEarningsBu.setForeground(new java.awt.Color(0, 0, 0));
        textEEarningsBu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textEEarningsBu.setToolTipText("");
        textEEarningsBu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMarcadorGanadores.add(textEEarningsBu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 50));

        textECostBu.setEditable(false);
        textECostBu.setBackground(new java.awt.Color(255, 255, 255));
        textECostBu.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        textECostBu.setForeground(new java.awt.Color(0, 0, 0));
        textECostBu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textECostBu.setToolTipText("");
        textECostBu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMarcadorGanadores.add(textECostBu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 110, 50));

        titulo64.setBackground(new java.awt.Color(0, 0, 0));
        titulo64.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo64.setForeground(new java.awt.Color(0, 0, 0));
        titulo64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo64.setText("Marcador");
        panelMarcadorGanadores.add(titulo64, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 20));

        PanelPrincipal.add(panelMarcadorGanadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 300, 140));

        panelTiempo.setBackground(new java.awt.Color(255, 102, 102));
        panelTiempo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTiempo.setForeground(new java.awt.Color(0, 0, 0));
        panelTiempo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo60.setBackground(new java.awt.Color(0, 0, 0));
        titulo60.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo60.setForeground(new java.awt.Color(0, 0, 0));
        titulo60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo60.setText("Control de tiempos");
        panelTiempo.add(titulo60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 20));

        textDaysRemainingBu.setEditable(false);
        textDaysRemainingBu.setBackground(new java.awt.Color(255, 255, 255));
        textDaysRemainingBu.setForeground(new java.awt.Color(0, 0, 0));
        textDaysRemainingBu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textDaysRemainingBu.setToolTipText("");
        textDaysRemainingBu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTiempo.add(textDaysRemainingBu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, 30));

        titulo59.setBackground(new java.awt.Color(0, 0, 0));
        titulo59.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo59.setForeground(new java.awt.Color(0, 0, 0));
        titulo59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo59.setText("Gestion de Trabajo");
        panelTiempo.add(titulo59, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 260, 20));

        PanelPrincipal.add(panelTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 300, 90));

        buttonSalir.setBackground(new java.awt.Color(255, 0, 0));
        buttonSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSalir.setForeground(new java.awt.Color(0, 0, 0));
        buttonSalir.setText("x");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });
        PanelPrincipal.add(buttonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 70, 40));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("2023 © Norangel Marin y Jenderson Quintero");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 636, 1000, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopSimulationActionPerformed
        
    }//GEN-LAST:event_btnStopSimulationActionPerformed

    private void btnStartSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartSimulationActionPerformed
        
    }//GEN-LAST:event_btnStartSimulationActionPerformed

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void textDaysRemainingBu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDaysRemainingBu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDaysRemainingBu5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel alta;
    private javax.swing.JLabel baja;
    private javax.swing.JButton btnStartSimulation;
    private javax.swing.JButton btnStopSimulation;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel media;
    private javax.swing.JPanel panelCarrera;
    private javax.swing.JPanel panelColasBugatti;
    private javax.swing.JPanel panelColasLamborguini;
    private javax.swing.JPanel panelIA;
    private javax.swing.JPanel panelMarcadorGanadores;
    private javax.swing.JPanel panelTiempo;
    private javax.swing.JTextField textCalidadAltaBugatti;
    private javax.swing.JTextField textCalidadBajaBugatti;
    private javax.swing.JTextField textCalidadMediaBugatti;
    private javax.swing.JTextField textDaysRemainingBu;
    private javax.swing.JTextField textDaysRemainingBu1;
    private javax.swing.JTextField textDaysRemainingBu5;
    private javax.swing.JTextField textDaysRemainingBu6;
    private javax.swing.JTextField textDaysRemainingBu7;
    private javax.swing.JTextField textDaysRemainingBu8;
    private javax.swing.JTextField textDaysRemainingBu9;
    private javax.swing.JTextField textECostBu;
    private javax.swing.JTextField textEEarningsBu;
    private javax.swing.JLabel titulo30;
    private javax.swing.JLabel titulo31;
    private javax.swing.JLabel titulo35;
    private javax.swing.JLabel titulo36;
    private javax.swing.JLabel titulo37;
    private javax.swing.JLabel titulo40;
    private javax.swing.JLabel titulo41;
    private javax.swing.JLabel titulo59;
    private javax.swing.JLabel titulo6;
    private javax.swing.JLabel titulo60;
    private javax.swing.JLabel titulo61;
    private javax.swing.JLabel titulo62;
    private javax.swing.JLabel titulo63;
    private javax.swing.JLabel titulo64;
    private javax.swing.JLabel tituloColasBugatti;
    private javax.swing.JLabel tituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
