package interfaz;

import javax.swing.JOptionPane;
import main.Administrator;
import main.Enterprise;
import main.IA;

/**
 *
 * @author Norangel Marin
 */
public class Interfaz extends javax.swing.JFrame {

    public Administrator admin;
    public IA ia;
    public Enterprise enterpriseBuga;
    public Enterprise enterpriseLambo;
    
    
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        tituloPrincipal = new javax.swing.JLabel();
        btnStartSimulation = new javax.swing.JButton();
        btnStopSimulation = new javax.swing.JButton();
        panelColasBugatti = new javax.swing.JPanel();
        tituloColasBugatti = new javax.swing.JLabel();
        alta = new javax.swing.JLabel();
        baja = new javax.swing.JLabel();
        media = new javax.swing.JLabel();
        textCalidadBajaBugatti1 = new javax.swing.JTextField();
        textCalidadBajaBugatti2 = new javax.swing.JTextField();
        textCalidadBajaBugatti3 = new javax.swing.JTextField();
        textCalidadBajaBugatti4 = new javax.swing.JTextField();
        alta1 = new javax.swing.JLabel();
        panelCarrera = new javax.swing.JPanel();
        titulo40 = new javax.swing.JLabel();
        titulo41 = new javax.swing.JLabel();
        textVehicleLam = new javax.swing.JTextField();
        textVehicleBu = new javax.swing.JTextField();
        panelColasLamborguini = new javax.swing.JPanel();
        titulo6 = new javax.swing.JLabel();
        textCalidadBajaBugatti5 = new javax.swing.JTextField();
        textCalidadBajaBugatti6 = new javax.swing.JTextField();
        textCalidadBajaBugatti7 = new javax.swing.JTextField();
        textCalidadBajaBugatti8 = new javax.swing.JTextField();
        alta2 = new javax.swing.JLabel();
        alta3 = new javax.swing.JLabel();
        media1 = new javax.swing.JLabel();
        baja1 = new javax.swing.JLabel();
        panelIA = new javax.swing.JPanel();
        titulo62 = new javax.swing.JLabel();
        textStatusIA = new javax.swing.JTextField();
        titulo63 = new javax.swing.JLabel();
        panelMarcadorGanadores = new javax.swing.JPanel();
        titulo61 = new javax.swing.JLabel();
        titulo30 = new javax.swing.JLabel();
        titulo31 = new javax.swing.JLabel();
        textCounterWinB = new javax.swing.JTextField();
        textCounterWinL = new javax.swing.JTextField();
        titulo64 = new javax.swing.JLabel();
        panelTiempo = new javax.swing.JPanel();
        titulo60 = new javax.swing.JLabel();
        inputTime = new javax.swing.JTextField();
        titulo59 = new javax.swing.JLabel();
        btnChangeTime = new javax.swing.JToggleButton();
        buttonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        PanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        PanelPrincipal.setForeground(new java.awt.Color(255, 255, 204));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        tituloPrincipal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        tituloPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        tituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPrincipal.setText("Simulación de Carreras");
        PanelPrincipal.add(tituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 740, 40));

        btnStartSimulation.setBackground(new java.awt.Color(0, 0, 0));
        btnStartSimulation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStartSimulation.setForeground(new java.awt.Color(255, 255, 255));
        btnStartSimulation.setText("Iniciar Simulación");
        btnStartSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartSimulationActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnStartSimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 340, 30));

        btnStopSimulation.setBackground(new java.awt.Color(0, 0, 0));
        btnStopSimulation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStopSimulation.setForeground(new java.awt.Color(255, 255, 255));
        btnStopSimulation.setText("Terminar Simulación");
        btnStopSimulation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStopSimulationMouseClicked(evt);
            }
        });
        PanelPrincipal.add(btnStopSimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 340, 30));

        panelColasBugatti.setBackground(new java.awt.Color(255, 102, 102));
        panelColasBugatti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasBugatti.setForeground(new java.awt.Color(0, 0, 0));
        panelColasBugatti.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloColasBugatti.setBackground(new java.awt.Color(0, 0, 0));
        tituloColasBugatti.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        tituloColasBugatti.setForeground(new java.awt.Color(0, 0, 0));
        tituloColasBugatti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloColasBugatti.setText("Colas de Calidad Bugatti");
        panelColasBugatti.add(tituloColasBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 310, 20));

        alta.setBackground(new java.awt.Color(0, 0, 0));
        alta.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        alta.setForeground(new java.awt.Color(0, 0, 0));
        alta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alta.setText("Refuerzo");
        panelColasBugatti.add(alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 90, -1));

        baja.setBackground(new java.awt.Color(0, 0, 0));
        baja.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        baja.setForeground(new java.awt.Color(0, 0, 0));
        baja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baja.setText("Baja");
        panelColasBugatti.add(baja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 90, -1));

        media.setBackground(new java.awt.Color(0, 0, 0));
        media.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        media.setForeground(new java.awt.Color(0, 0, 0));
        media.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        media.setText("Media");
        panelColasBugatti.add(media, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 90, -1));

        textCalidadBajaBugatti1.setEditable(false);
        textCalidadBajaBugatti1.setBackground(new java.awt.Color(255, 255, 255));
        textCalidadBajaBugatti1.setForeground(new java.awt.Color(0, 0, 0));
        textCalidadBajaBugatti1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCalidadBajaBugatti1.setToolTipText("");
        textCalidadBajaBugatti1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasBugatti.add(textCalidadBajaBugatti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 60, 310));

        textCalidadBajaBugatti2.setEditable(false);
        textCalidadBajaBugatti2.setBackground(new java.awt.Color(255, 255, 255));
        textCalidadBajaBugatti2.setForeground(new java.awt.Color(0, 0, 0));
        textCalidadBajaBugatti2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCalidadBajaBugatti2.setToolTipText("");
        textCalidadBajaBugatti2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasBugatti.add(textCalidadBajaBugatti2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 60, 310));

        textCalidadBajaBugatti3.setEditable(false);
        textCalidadBajaBugatti3.setBackground(new java.awt.Color(255, 255, 255));
        textCalidadBajaBugatti3.setForeground(new java.awt.Color(0, 0, 0));
        textCalidadBajaBugatti3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCalidadBajaBugatti3.setToolTipText("");
        textCalidadBajaBugatti3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasBugatti.add(textCalidadBajaBugatti3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 60, 310));

        textCalidadBajaBugatti4.setEditable(false);
        textCalidadBajaBugatti4.setBackground(new java.awt.Color(255, 255, 255));
        textCalidadBajaBugatti4.setForeground(new java.awt.Color(0, 0, 0));
        textCalidadBajaBugatti4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCalidadBajaBugatti4.setToolTipText("");
        textCalidadBajaBugatti4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasBugatti.add(textCalidadBajaBugatti4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 60, 310));

        alta1.setBackground(new java.awt.Color(0, 0, 0));
        alta1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        alta1.setForeground(new java.awt.Color(0, 0, 0));
        alta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alta1.setText("Alta");
        panelColasBugatti.add(alta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 90, -1));

        PanelPrincipal.add(panelColasBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 310, 390));

        panelCarrera.setBackground(new java.awt.Color(255, 102, 102));
        panelCarrera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCarrera.setForeground(new java.awt.Color(0, 0, 0));
        panelCarrera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo40.setBackground(new java.awt.Color(0, 0, 0));
        titulo40.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo40.setForeground(new java.awt.Color(0, 0, 0));
        titulo40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo40.setText("(Vehiculos en la IA)");
        panelCarrera.add(titulo40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 20));

        titulo41.setBackground(new java.awt.Color(0, 0, 0));
        titulo41.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo41.setForeground(new java.awt.Color(0, 0, 0));
        titulo41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo41.setText("Carrera");
        panelCarrera.add(titulo41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 20));

        textVehicleLam.setEditable(false);
        textVehicleLam.setBackground(new java.awt.Color(255, 255, 255));
        textVehicleLam.setForeground(new java.awt.Color(0, 0, 0));
        textVehicleLam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textVehicleLam.setToolTipText("");
        textVehicleLam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCarrera.add(textVehicleLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, 50));

        textVehicleBu.setEditable(false);
        textVehicleBu.setBackground(new java.awt.Color(255, 255, 255));
        textVehicleBu.setForeground(new java.awt.Color(0, 0, 0));
        textVehicleBu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textVehicleBu.setToolTipText("");
        textVehicleBu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCarrera.add(textVehicleBu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 50));

        PanelPrincipal.add(panelCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 300, 140));

        panelColasLamborguini.setBackground(new java.awt.Color(255, 102, 102));
        panelColasLamborguini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasLamborguini.setForeground(new java.awt.Color(0, 0, 0));
        panelColasLamborguini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo6.setBackground(new java.awt.Color(0, 0, 0));
        titulo6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo6.setForeground(new java.awt.Color(0, 0, 0));
        titulo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo6.setText("Colas de Calidad Lamborghini");
        panelColasLamborguini.add(titulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 310, 20));

        textCalidadBajaBugatti5.setEditable(false);
        textCalidadBajaBugatti5.setBackground(new java.awt.Color(255, 255, 255));
        textCalidadBajaBugatti5.setForeground(new java.awt.Color(0, 0, 0));
        textCalidadBajaBugatti5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCalidadBajaBugatti5.setToolTipText("");
        textCalidadBajaBugatti5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasLamborguini.add(textCalidadBajaBugatti5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 60, 310));

        textCalidadBajaBugatti6.setEditable(false);
        textCalidadBajaBugatti6.setBackground(new java.awt.Color(255, 255, 255));
        textCalidadBajaBugatti6.setForeground(new java.awt.Color(0, 0, 0));
        textCalidadBajaBugatti6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCalidadBajaBugatti6.setToolTipText("");
        textCalidadBajaBugatti6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasLamborguini.add(textCalidadBajaBugatti6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 60, 310));

        textCalidadBajaBugatti7.setEditable(false);
        textCalidadBajaBugatti7.setBackground(new java.awt.Color(255, 255, 255));
        textCalidadBajaBugatti7.setForeground(new java.awt.Color(0, 0, 0));
        textCalidadBajaBugatti7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCalidadBajaBugatti7.setToolTipText("");
        textCalidadBajaBugatti7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasLamborguini.add(textCalidadBajaBugatti7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 60, 310));

        textCalidadBajaBugatti8.setEditable(false);
        textCalidadBajaBugatti8.setBackground(new java.awt.Color(255, 255, 255));
        textCalidadBajaBugatti8.setForeground(new java.awt.Color(0, 0, 0));
        textCalidadBajaBugatti8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCalidadBajaBugatti8.setToolTipText("");
        textCalidadBajaBugatti8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColasLamborguini.add(textCalidadBajaBugatti8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 60, 310));

        alta2.setBackground(new java.awt.Color(0, 0, 0));
        alta2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        alta2.setForeground(new java.awt.Color(0, 0, 0));
        alta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alta2.setText("Refuerzo");
        panelColasLamborguini.add(alta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 90, -1));

        alta3.setBackground(new java.awt.Color(0, 0, 0));
        alta3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        alta3.setForeground(new java.awt.Color(0, 0, 0));
        alta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alta3.setText("Alta");
        panelColasLamborguini.add(alta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 90, -1));

        media1.setBackground(new java.awt.Color(0, 0, 0));
        media1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        media1.setForeground(new java.awt.Color(0, 0, 0));
        media1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        media1.setText("Media");
        panelColasLamborguini.add(media1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 90, -1));

        baja1.setBackground(new java.awt.Color(0, 0, 0));
        baja1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        baja1.setForeground(new java.awt.Color(0, 0, 0));
        baja1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baja1.setText("Baja");
        panelColasLamborguini.add(baja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 90, -1));

        PanelPrincipal.add(panelColasLamborguini, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 310, 390));

        panelIA.setBackground(new java.awt.Color(255, 102, 102));
        panelIA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelIA.setForeground(new java.awt.Color(0, 0, 0));
        panelIA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo62.setBackground(new java.awt.Color(0, 0, 0));
        titulo62.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo62.setForeground(new java.awt.Color(0, 0, 0));
        titulo62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo62.setText("Status IA");
        panelIA.add(titulo62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 20));

        textStatusIA.setEditable(false);
        textStatusIA.setBackground(new java.awt.Color(255, 255, 255));
        textStatusIA.setForeground(new java.awt.Color(0, 0, 0));
        textStatusIA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textStatusIA.setToolTipText("");
        textStatusIA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelIA.add(textStatusIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, 30));

        titulo63.setBackground(new java.awt.Color(0, 0, 0));
        titulo63.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo63.setForeground(new java.awt.Color(0, 0, 0));
        titulo63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo63.setText("Gestion de Trabajo");
        panelIA.add(titulo63, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 260, 20));

        PanelPrincipal.add(panelIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 300, 90));

        panelMarcadorGanadores.setBackground(new java.awt.Color(255, 102, 102));
        panelMarcadorGanadores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMarcadorGanadores.setForeground(new java.awt.Color(0, 0, 0));
        panelMarcadorGanadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo61.setBackground(new java.awt.Color(0, 0, 0));
        titulo61.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo61.setForeground(new java.awt.Color(0, 0, 0));
        titulo61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo61.setText("(Conteo de carreras ganadas)");
        panelMarcadorGanadores.add(titulo61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 20));

        titulo30.setBackground(new java.awt.Color(0, 0, 0));
        titulo30.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        titulo30.setForeground(new java.awt.Color(0, 0, 0));
        titulo30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo30.setText("Lamborghini");
        panelMarcadorGanadores.add(titulo30, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 110, -1));

        titulo31.setBackground(new java.awt.Color(0, 0, 0));
        titulo31.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        titulo31.setForeground(new java.awt.Color(0, 0, 0));
        titulo31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo31.setText("Bugatti");
        panelMarcadorGanadores.add(titulo31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, -1));

        textCounterWinB.setEditable(false);
        textCounterWinB.setBackground(new java.awt.Color(255, 255, 255));
        textCounterWinB.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        textCounterWinB.setForeground(new java.awt.Color(0, 0, 0));
        textCounterWinB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCounterWinB.setToolTipText("");
        textCounterWinB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMarcadorGanadores.add(textCounterWinB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 50));

        textCounterWinL.setEditable(false);
        textCounterWinL.setBackground(new java.awt.Color(255, 255, 255));
        textCounterWinL.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        textCounterWinL.setForeground(new java.awt.Color(0, 0, 0));
        textCounterWinL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCounterWinL.setToolTipText("");
        textCounterWinL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMarcadorGanadores.add(textCounterWinL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 110, 50));

        titulo64.setBackground(new java.awt.Color(0, 0, 0));
        titulo64.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo64.setForeground(new java.awt.Color(0, 0, 0));
        titulo64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo64.setText("Marcador");
        panelMarcadorGanadores.add(titulo64, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 20));

        PanelPrincipal.add(panelMarcadorGanadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 300, 140));

        panelTiempo.setBackground(new java.awt.Color(255, 102, 102));
        panelTiempo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTiempo.setForeground(new java.awt.Color(0, 0, 0));
        panelTiempo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo60.setBackground(new java.awt.Color(0, 0, 0));
        titulo60.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo60.setForeground(new java.awt.Color(0, 0, 0));
        titulo60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo60.setText("Control de tiempo");
        panelTiempo.add(titulo60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 20));

        inputTime.setBackground(new java.awt.Color(255, 255, 255));
        inputTime.setForeground(new java.awt.Color(0, 0, 0));
        inputTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputTime.setToolTipText("");
        inputTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTiempo.add(inputTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 30));

        titulo59.setBackground(new java.awt.Color(0, 0, 0));
        titulo59.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo59.setForeground(new java.awt.Color(0, 0, 0));
        titulo59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo59.setText("Gestion de Trabajo");
        panelTiempo.add(titulo59, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 260, 20));

        btnChangeTime.setText("Cambiar");
        btnChangeTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangeTimeMouseClicked(evt);
            }
        });
        panelTiempo.add(btnChangeTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 110, 30));

        PanelPrincipal.add(panelTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 300, 90));

        buttonSalir.setBackground(new java.awt.Color(255, 0, 0));
        buttonSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSalir.setForeground(new java.awt.Color(0, 0, 0));
        buttonSalir.setText("x");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });
        PanelPrincipal.add(buttonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 70, 40));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("2023 © Norangel Marin y Jenderson Quintero");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 636, 1000, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateDataView() {
        this.textStatusIA.setText(this.ia.getStatusIA());
        this.textCounterWinB.setText(Integer.toString(this.enterpriseBuga.getRacersWin()));
        this.textCounterWinL.setText(Integer.toString(this.enterpriseLambo.getRacersWin()));
        
        this.textVehicleBu.setText(Integer.toString(this.admin.getV1Selected().getuId()));
        this.textVehicleLam.setText(Integer.toString(this.admin.getV2Selected().getuId()));
        
    }
    
    private void btnStartSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartSimulationActionPerformed
        this.enterpriseBuga = new Enterprise();
        this.enterpriseLambo = new Enterprise();
        this.ia = new IA();
        
        this.admin = new Administrator(this.enterpriseBuga, this.enterpriseLambo, this.ia, this);
        
        this.admin.loadCarsInit();
        this.admin.start();
    }//GEN-LAST:event_btnStartSimulationActionPerformed

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void btnStopSimulationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopSimulationMouseClicked
        this.admin.stopPlant();
    }//GEN-LAST:event_btnStopSimulationMouseClicked

    private void btnChangeTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeTimeMouseClicked
        try {
            Long newTime = Long.valueOf(this.inputTime.getText());
            if (this.admin != null) {
                this.admin.setTimeSimulation(newTime);
            } else {
                JOptionPane.showMessageDialog(null, "StartSimulación", "Inicie la simulación",0);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Número inválido", "El tiempo ingresado no es un número",0);
        }
        
        
    }//GEN-LAST:event_btnChangeTimeMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel alta;
    private javax.swing.JLabel alta1;
    private javax.swing.JLabel alta2;
    private javax.swing.JLabel alta3;
    private javax.swing.JLabel baja;
    private javax.swing.JLabel baja1;
    private javax.swing.JToggleButton btnChangeTime;
    private javax.swing.JButton btnStartSimulation;
    private javax.swing.JButton btnStopSimulation;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JTextField inputTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel media;
    private javax.swing.JLabel media1;
    private javax.swing.JPanel panelCarrera;
    private javax.swing.JPanel panelColasBugatti;
    private javax.swing.JPanel panelColasLamborguini;
    private javax.swing.JPanel panelIA;
    private javax.swing.JPanel panelMarcadorGanadores;
    private javax.swing.JPanel panelTiempo;
    private javax.swing.JTextField textCalidadBajaBugatti1;
    private javax.swing.JTextField textCalidadBajaBugatti2;
    private javax.swing.JTextField textCalidadBajaBugatti3;
    private javax.swing.JTextField textCalidadBajaBugatti4;
    private javax.swing.JTextField textCalidadBajaBugatti5;
    private javax.swing.JTextField textCalidadBajaBugatti6;
    private javax.swing.JTextField textCalidadBajaBugatti7;
    private javax.swing.JTextField textCalidadBajaBugatti8;
    private javax.swing.JTextField textCounterWinB;
    private javax.swing.JTextField textCounterWinL;
    private javax.swing.JTextField textStatusIA;
    private javax.swing.JTextField textVehicleBu;
    private javax.swing.JTextField textVehicleLam;
    private javax.swing.JLabel titulo30;
    private javax.swing.JLabel titulo31;
    private javax.swing.JLabel titulo40;
    private javax.swing.JLabel titulo41;
    private javax.swing.JLabel titulo59;
    private javax.swing.JLabel titulo6;
    private javax.swing.JLabel titulo60;
    private javax.swing.JLabel titulo61;
    private javax.swing.JLabel titulo62;
    private javax.swing.JLabel titulo63;
    private javax.swing.JLabel titulo64;
    private javax.swing.JLabel tituloColasBugatti;
    private javax.swing.JLabel tituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
